---
- name: Setup frontend container
  hosts: frontend_servers
  remote_user: ubuntu
  become: yes
  vars:
    PORT: "8081"
    BACKEND_URL: "http://{{ hostvars['backend_alb']['dns_name'] }}:80"
  tasks:
    - name: Run frontend container
      community.docker.docker_container:
        name: frontend
        image: rmitdominichynes/sdo-2025:frontend
        restart_policy: always
        ports:
          - "8081:8081"
        env:
          PORT: "{{ PORT }}"
          BACKEND_URL: "{{ BACKEND_URL }}"