name: Deploy Infrastructure and Application
on:
  push:
    branches:
      - test
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Servers Deployment
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4
      
      - name: Configure Ansible and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible curl python3-pip
          ansible-galaxy collection install community.docker
          pip3 install docker
      
      - name: Setup SSH key
        run: |
          printf '/home/runner/.ssh/aws_ssh\n\n\n' | ssh-keygen -t rsa -b 4096
          chmod 600 /home/runner/.ssh/aws_ssh
          chmod 644 /home/runner/.ssh/aws_ssh.pub
          printf "ssh_public_key=\"/home/runner/.ssh/aws_ssh.pub\"\nallow_all_ip_addresses_to_db_server=true\n" > $GITHUB_WORKSPACE/terraform/terraform.auto.tfvars
      
      - name: View SSH Key
        run: |
          cat /home/runner/.ssh/aws_ssh
          cat /home/runner/.ssh/aws_ssh.pub
      
      - name: Fetch current IP and configure Terraform variables
        run: printf "ip_address = \"$(curl -s https://api.ipify.org)\"" > terraform/ip.auto.tfvars
      
      - name: Initiate Terraform session
        run: terraform -chdir=./terraform init
      
      - name: Validate Terraform configuration
        run: terraform -chdir=./terraform validate
      
      - name: Deploy infrastructure
        run: terraform -chdir=./terraform apply -auto-approve
      
      - name: Wait for servers to be ready
        run: sleep 60
      
      - name: Run Docker playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/docker-playbook.yml \
            --private-key /home/runner/.ssh/aws_ssh \
            --ssh-common-args='-o StrictHostKeyChecking=accept-new'
      
      - name: Run Database playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/db-playbook.yml \
            --private-key /home/runner/.ssh/aws_ssh \
            --ssh-common-args='-o StrictHostKeyChecking=accept-new'
      
      - name: Run Backend playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/backend-playbook.yml \
            --private-key /home/runner/.ssh/aws_ssh \
            --ssh-common-args='-o StrictHostKeyChecking=accept-new'
      
      - name: Run Frontend playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/frontend-playbook.yml \
            --private-key /home/runner/.ssh/aws_ssh \
            --ssh-common-args='-o StrictHostKeyChecking=accept-new'
      
      - name: Terminate infrastructure
        if: ${{ !success() }}
        run: terraform -chdir=./terraform destroy -auto-approve
